---
- name: Setup redis-server and firewall settings on a Debian host

  # Specify the hosts you want to target
  hosts: redis

  remote_user: team

  vars:
    system_packages: ["redis-server"]

  tasks:
    - name: Update apt
      become: yes
      become_user: root
      apt: update_cache=yes

    - name: Install required system packages
      become: yes
      become_user: root
      apt: name={{ system_packages }} state=latest

    - name: UFW - Allow Redis connections
      become: yes
      become_user: root
      ufw:
        rule: allow
        port: 6379
        proto: tcp
        src: 10.122.0.0/20

    - name: Enable redis-server to start on boot
      become: yes
      become_user: root
      systemd:
        name: redis-server
        enabled: yes

    - name: Start redis-server server
      become: yes
      become_user: root
      systemd:
        name: redis-server
        state: started
